#!/usr/bin/env python3
import subprocess
from collections import OrderedDict
import sys
import json
from os.path import expanduser

def stderr(s):
    sys.stderr.write(s)
    sys.stderr.write('\n')

orderedjson = json.JSONDecoder(object_pairs_hook=OrderedDict) 

shortcuts = OrderedDict()

with open(expanduser('~/.qwe'), 'r') as fh:
    for line in fh.readlines():
        stripped_line = line.strip()
        if not stripped_line or stripped_line.startswith('#'):  # skip comments
            continue
        shortcut, command = stripped_line.split(' ', 1)
        shortcuts[shortcut] = command.strip() # remove preceeding spaces

helpText = '\n'.join([
    '%d %s' % (idx + 1, shortcut)
    for idx, (shortcut, command) in enumerate(shortcuts.items())
])

def get_shortcut(cmd):
    if cmd.isnumeric():
        shortcut_num = int(cmd)
        min_num, max_num = 1, len(shortcuts)
        if max_num >= shortcut_num >= min_num:
            return list(shortcuts.items())[shortcut_num - 1][1]
        else:
            print('Shortcut number must be between %d and %d.' % (max_num, min_num))
    else:
        return shortcuts.get(cmd)

def execute(cmd):
    stderr('$ %s' % cmd)
    try:
        subprocess.call(cmd, shell=True)
    except KeyboardInterrupt:
        sys.exit(0)

args = sys.argv[1:]
if len(args):
    cmd = get_shortcut(args[0])
    if cmd is None:
        print(helpText)
        print('Unknown command %s' % args[0])
        sys.exit(1)
    execute(cmd + ' '.join(args[1:]))
else:
    cmd = None
    while cmd is None:
        print(helpText)
        try:
            input_cmd = input('Please select a shortcut: \n').split(' ')
            cmd = get_shortcut(input_cmd[0])
            if cmd is None:
                print('Unknown command %s' % input_cmd)
            else:
                cmd += ' '.join(input_cmd[1:])
        except KeyboardInterrupt:
            sys.exit(0)
    execute(cmd)


